spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Osm
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        type: trace

osm:
  db:
    init:
      enabled: false
      file-path: C:\Users\Tigrulya\Desktop\Study\IdeaProjects\DistributedSystems\OsmXmlProcessor\RU-NVS.osm.bz2
